In [11]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import * 
import matlab.engine

In [4]:
rating_matrix_csr = load_npz('../Step 1 - Movielens Data preprocessing/ml-latest/sparse_matrix_ml-latest.npz').tocsr()

In [51]:
rating_matrix_csr = rating_matrix_csr[0:int(0.1 * rating_matrix_csr.shape[0]),:]

In [61]:
def dist(i, j):
    if i.getnnz() == 0 or j.getnnz() == 0:
        print("cold user!")
        return 0
    mean_i = i.sum()/i.getnnz()
    mean_j = j.sum()/j.getnnz()
    lap = i.toarray() * j.toarray()
    if len(lap.nonzero()[0]) == 0:
        return 0
    else:
        lap_i = i[lap.nonzero()] - np.ones((len(lap.nonzero()[0]))) * mean_i
        lap_j = j[lap.nonzero()] - np.ones((len(lap.nonzero()[0]))) * mean_j
        if lap_i.sum()==0 or lap_j.sum()==0:            
            return 0
        else:
            ppc = np.multiply(lap_i, lap_j).sum()/((np.multiply(lap_i, lap_i).sum() * np.multiply(lap_j, lap_j).sum()) ** 0.5)
            return 1 - ppc

In [62]:
for i in range(rating_matrix_csr.shape[0]):
    dist(rating_matrix_csr[i,:], rating_matrix_csr[452,:])

cold user!


KeyboardInterrupt: 

## k-means

In [22]:
import random
import sys
def k_means(data,k):  
    
    #random generate cluster_center  
    sample_num=data.shape[0]  
    center_index=random.sample(range(sample_num),k)  
    cluster_cen=data[center_index,:]  
  
    is_change=1  
    cat=np.zeros(sample_num)    
  
    while is_change: 
        print(is_change)
        is_change=0    
        for i in range(sample_num):  
            min_distance=100000  
            min_index=0  
  
            for j in range(k):  
                distance=dist(data[i,:], cluster_cen[j,:])  
                if distance < min_distance:  
                    min_distance=distance  
                    min_index=j+1  
  
            if cat[i]!=min_index:  
                is_change=1  
                cat[i]=min_index  
        for j in range(k):  
            cluster_cen[j]=np.mean(data[cat==(j+1)],axis=0)  
  
    return cat,cluster_cen  

In [ ]:
k_means(rating_matrix_csr, 5)

1


c:\users\zhaozihan\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.


15
2
[[ 0.  0.]]
15
2
[[ 0.  0.]]
15
2
[[ 0.  0.]]


c:\users\zhaozihan\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in double_scalars
